

# Configuring https://pre-commit.ci/
ci:
    autoupdate_schedule: monthly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.3.0
      hooks:
        - id: ruff
    - repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.8.0
      hooks:
          - id: mypy
            additional_dependencies:
                - types-setuptools
    - repo: https://github.com/codespell-project/codespell
      # Configuration for codespell is in pyproject.toml
      rev: v2.2.6
      hooks:
      - id: codespell
        additional_dependencies:
        - tomli
